# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem 'sinatra'
gem 'skywalking', '~> 0.1.0'
gem "rackup", "~> 2.2"
gem "puma", "~> 6.5"

gem "redis", "~> 5.3"
gem "elasticsearch", "8.0.0"
gem 'dalli', '~> 3.2'