spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: "admin"
    password: "123456"

  data:
    redis:
      host: localhost
mq:
  email:
    queue-name: java-queue
    exchange-name: java-exchange
    routing-key-name: java-routing-key
server:
  port: 9001
